// Automatically generated by astro-icon
// 87a969c54d8b5739b098627b9f68e029dcc9fa2629fa77d5d334575326220601

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "arrowLeft"
		| "arrowRight"
		| "email"
		| "facebook"
		| "flickr"
		| "instagram"
		| "linkedin"
		| "twitter"
		| "web"
		| "youtube";
}