// Automatically generated by astro-icon
// 6e71b24193b97cee1d7bc356c2ddd5c872671a80baebe5c566a438d85660d871

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "arrowRight"
		| "facebook"
		| "flickr"
		| "instagram"
		| "link"
		| "linkedin"
		| "twitter"
		| "youtube";
}