// Automatically generated by astro-icon
// 3e87d52ad2ad4e18f984deaded288607e3cc9696982b805d8d7f7509712018ae

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "arrowRight"
		| "facebook"
		| "flickr"
		| "instagram"
		| "linkedin"
		| "twitter"
		| "web"
		| "youtube";
}