FROM node:22-slim AS runtime
WORKDIR /app

COPY package*.json .

RUN npm ci

COPY . .

ARG CONTENTFUL_SPACE
ENV CONTENTFUL_SPACE=$CONTENTFUL_SPACE

ARG CONTENTFUL_ENVIRONMENT
ENV CONTENTFUL_ENVIRONMENT=$CONTENTFUL_ENVIRONMENT

ARG CONTENTFUL_API_TOKEN
ENV CONTENTFUL_API_TOKEN=$CONTENTFUL_API_TOKEN

ARG AIRTABLE_BASE
ENV AIRTABLE_BASE=$AIRTABLE_BASE

ARG AIRTABLE_API_KEY
ENV AIRTABLE_API_KEY=$AIRTABLE_API_KEY

RUN npm run build

ENV HOST=0.0.0.0
ENV PORT=4321
EXPOSE 4321
CMD node ./dist/server/entry.mjs
