FROM node:lts AS runtime
WORKDIR /app

COPY . .

RUN npm install

ARG CONTENTFUL_SPACE
ENV CONTENTFUL_SPACE=$CONTENTFUL_SPACE

ARG CONTENTFUL_ENVIRONMENT
ENV CONTENTFUL_ENVIRONMENT=$CONTENTFUL_ENVIRONMENT

ARG CONTENTFUL_API_TOKEN
ENV CONTENTFUL_API_TOKEN=$CONTENTFUL_API_TOKEN

RUN npm run build

ENV HOST=0.0.0.0
ENV PORT=4321
EXPOSE 4321
CMD node ./dist/server/entry.mjs
