export const SPONSOR_LIST_FILTER_TAG_KEY = "FRONT24";

export const SPONSOR_LIST_CATEGORY_SORTING_KEYS = [
  "PRESENTING SPONSOR",
  "DIAMOND",
  "PLATINUM",
  "GOLD",
  "SILVER",
  "CONTRIBUTING",
];
