const TAG_KEY = "FRONT26";

export const SPONSOR_LIST_FILTER_TAG_KEY = TAG_KEY;
export const SPONSOR_LIST_CATEGORY_SORTING_KEYS = [
	"PRESENTING SPONSOR",
	"DIAMOND",
	"PLATINUM",
	"GOLD",
	"SILVER",
	"CONTRIBUTING",
];

export const SPEAKER_YEAR_TAG_KEY = TAG_KEY;
export const TALK_YEAR_TAG_KEY = TAG_KEY;
export const WORKSHOP_YEAR_TAG_KEY = TAG_KEY;
